version: '3.3'

services:
  store-api-rs:
    build:
      context: .
      dockerfile: Dockerfile
    image: store-api-rs
    container_name: store-api-rs
    ports:
      - 8888:8888
    volumes:
      - "./config:/data/resources/config"
      - "./data:/data/sqlite"
    environment:
      TZ : 'Asia/Shanghai'
      LANG: 'C.UTF-8'
      LC_ALL: 'C.UTF-8'
